id: I58F66FBB
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W1KG12679
  ocr_info:
    timestamp: 03/20/23T16:45:41
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-27 12:27:28.741587+00:00
last_modified: 2024-02-27 12:27:28.741595+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12679
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12679
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་གི་འབྲུ་འགྲེལ་དབུ་མའི་ལམ་གྱི་སྒྲོན་མ།
  languages:
  - bo
  author: འབྲུག་ཆེན ༠༤་པདྨ་དཀར་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9713780997492337
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG12921:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12921
      total_pages: 193
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12921.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9713780997492337
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
